In [2]:
import pandas as pd

In [ ]:

#Questão 1
data1= [{'leonardo':5.4, 'nicolas':11.99, 'alisson':4.5, 'adriano':6.0, 'gustavo':8.3}]
df1= pd.DataFrame(data1)
df1

   leonardo  nicolas  alisson  adriano  gustavo
0       5.4    11.99      4.5      6.0      8.3

In [13]:
# QUestão 2

data2= [{'nome': 'ana', 'cargo': 'analista'},{'nome': 'bruno', 'cargo': 'gerente', 'bonus': 500}]
df2= pd.DataFrame(data2)
df2

# Ana esta com  o valor NAN em "bonus", porque a coluna "bonus" foi 
# adicionada no segundo dicionario mas não no primeiro, que e aonde ana é representada
# por isso, o valor ficou ausente e foi preenchido por NAN (Not a Number).

    nome     cargo  bonus
0    ana  analista    NaN
1  bruno   gerente  500.0

In [17]:
# QUestão 3 

data3= {'nome': pd.Series(['maçã','banana', 'uva'], index= ['p1', 'p2', 'p3']),
        'preços': pd.Series(['R$10,50', 'R$5,90', 'R$2,45'], index= ['p1', 'p2', 'p3'])}
df3= pd.DataFrame(data3)
df3

      nome   preços
p1    maçã  R$10,50
p2  banana   R$5,90
p3     uva   R$2,45

In [22]:
# Questão 4

data4= [{'Sede_A':2500, 'Sede_B':3700}]
df4= pd.DataFrame(data4)
df4 ['Total_Vendas']= df4['Sede_A']+df4['Sede_B']
df4 ['Imposto']= df4['Sede_A'] * 10/100
df4

   Sede_A  Sede_B  Total_Vendas  Imposto
0    2500    3700          6200    250.0

In [30]:
# ----------------Questão 5----------------

data5= {'Clientes': pd.Series(['sergio','paulo', 'lucas']),
        'CPF': pd.Series(['154.877.990-32', '677.635.400-60', '308.142.040-74']),
        'Telefone': pd.Series(['9532539680', '2830961338', '3424936280'])}
df5 = pd.DataFrame(data5)
df5

  Clientes             CPF    Telefone
0   sergio  154.877.990-32  9532539680
1    paulo  677.635.400-60  2830961338
2    lucas  308.142.040-74  3424936280

In [31]:
# Excluindo a coluna "CPF" utilisando o comando del.

del df5['CPF']
df5

  Clientes    Telefone
0   sergio  9532539680
1    paulo  2830961338
2    lucas  3424936280

In [32]:
# Excluindo a coluna "Telefone" usando o método pop()

df5.pop('Telefone')
df5
# ----------------FIM questão 5 ----------------

  Clientes
0   sergio
1    paulo
2    lucas

In [ ]:
#----------------Questão 6----------------

data6= {'Área': pd.Series(['8.515.767 km²','2.780.400 km²', '756.102 km²'], index=['Brasil', 'Argentina', 'Chile']),
        'População': pd.Series(['203.062.512', '46.234.830', '19.629.590'], index=['Brasil', 'Argentina', 'Chile']),
        'Telefone': pd.Series(['33 anos', '32 anos', '35 anos'], index=['Brasil', 'Argentina', 'Chile'])}
df6= pd.DataFrame(data6)
df6

                    Área    População Telefone
Brasil     8.515.767 km²  203.062.512  33 anos
Argentina  2.780.400 km²   46.234.830  32 anos
Chile        756.102 km²   19.629.590  35 anos

In [ ]:
# Utilisando o m ́etodo loc para
# recuperar e imprimir apenas os dados referentes ao ’Brasil’.