In [1]:
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

In [23]:
df = pd.read_csv(r"C:\Users\nicol\Desktop\dashbord\financiamentoPecuaria.csv" , encoding='utf8' , sep=';')
df.head()

,Localidade,Variável,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Abadia de Goiás,Financiamentos à Pecuária - Custeio - Valor (R$),"330.195,67","726.987,76","566.675,99","625.422,82","682.545,53","887.641,14",1.304.629,2.409.683,3.396.983,0,3.101.003
1,Abadiânia,Financiamentos à Pecuária - Custeio - Valor (R$),"8.037.554,05","10.224.774,03","8.207.670,93","5.867.364,20","12.149.754,18","4.823.481,46",7.001.505,13.228.345,14.931.771,1.247.010,10.357.766
2,Acreúna,Financiamentos à Pecuária - Custeio - Valor (R$),"14.383.002,58","13.631.427,66","7.261.516,43","6.932.883,38","8.259.436,29","7.065.726,58",6.453.869,6.836.953,14.942.521,4.326.823,8.627.573
3,Adelândia,Financiamentos à Pecuária - Custeio - Valor (R$),"2.602.870,67","2.437.096,08","1.676.603,53","1.438.599,15","2.389.589,90","2.218.052,03",3.459.716,4.529.872,10.477.717,1.956.258,9.923.722
4,Água Fria de Goiás,Financiamentos à Pecuária - Custeio - Valor (R$),"2.488.538,70","3.674.710,53","1.416.654,80","874.106,93","9.283.948,96","4.196.060,34",5.588.390,1.512.845,5.446.464,2.065.800,9.611.876

In [ ]:
#troca todos os '-' por zero
df= df.replace('-', 0)
df.head(100)

,Localidade,Variável,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Abadia de Goiás,Financiamentos à Pecuária - Custeio - Valor (R$),"330.195,67","726.987,76","566.675,99","625.422,82","682.545,53","887.641,14",1.304.629,2.409.683,3.396.983,0,3.101.003
1,Abadiânia,Financiamentos à Pecuária - Custeio - Valor (R$),"8.037.554,05","10.224.774,03","8.207.670,93","5.867.364,20","12.149.754,18","4.823.481,46",7.001.505,13.228.345,14.931.771,1.247.010,10.357.766
2,Acreúna,Financiamentos à Pecuária - Custeio - Valor (R$),"14.383.002,58","13.631.427,66","7.261.516,43","6.932.883,38","8.259.436,29","7.065.726,58",6.453.869,6.836.953,14.942.521,4.326.823,8.627.573
3,Adelândia,Financiamentos à Pecuária - Custeio - Valor (R$),"2.602.870,67","2.437.096,08","1.676.603,53","1.438.599,15","2.389.589,90","2.218.052,03",3.459.716,4.529.872,10.477.717,1.956.258,9.923.722
4,Água Fria de Goiás,Financiamentos à Pecuária - Custeio - Valor (R$),"2.488.538,70","3.674.710,53","1.416.654,80","874.106,93","9.283.948,96","4.196.060,34",5.588.390,1.512.845,5.446.464,2.065.800,9.611.876
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Goianira,Financiamentos à Pecuária - Custeio - Valor (R$),"1.340.717,45","5.877.008,35","6.396.971,89","1.725.668,93","1.232.422,11","1.101.453,49",2.091.972,3.145.652,1.831.412,0,1.574.291
96,Goiás,Financiamentos à Pecuária - Custeio - Valor (R$),"31.112.826,50","32.087.778,91","33.690.467,61","35.396.269,19","37.499.191,44","50.803.471,70",51.068.353,92.331.266,94.094.387,19.335.374,123.257.634
97,Goiatuba,Financiamentos à Pecuária - Custeio - Valor (R$),"15.683.845,86","12.786.430,25","13.959.995,60","17.119.872,74","12.605.923,72","11.240.712,78",11.123.900,13.817.261,13.011.554,3.206.000,23.661.811
98,Gouvelândia,Financiamentos à Pecuária - Custeio - Valor (R$),"6.570.517,34","6.253.710,52","8.106.761,11","9.815.920,22","10.813.099,37","12.838.891,83",8.998.019,11.714.748,5.040.566,9.097.640,4.999.738
99,Guapó,Financiamentos à Pecuária - Custeio - Valor (R$),"6.238.595,20","3.824.116,84","8.232.153,24","11.569.572,85","7.792.705,89","17.226.431,33",10.835.287,16.639.678,17.798.764,3.186.342,13.042.660

In [16]:
#Verificando o tipo de dados das colunas
df.dtypes

Localidade    str
Variável      str
2014          str
2015          str
2016          str
2017          str
2018          str
2019          str
2020          str
2021          str
2022          str
2023          str
2024          str
dtype: object

In [17]:
# Verificando o tipo de dado das colunas
tipos = df['2014'].apply(type)
tipos

0      <class 'str'>
1      <class 'str'>
2      <class 'str'>
3      <class 'str'>
4      <class 'str'>
           ...
241    <class 'str'>
242    <class 'str'>
243    <class 'str'>
244    <class 'str'>
245    <class 'str'>
Name: 2014, Length: 246, dtype: object

In [27]:
for col in df.columns[1:]:
    df[col] = pd.to_numeric(
        df[col].astype(str).str.replace('.', '', regex=False).str.replace(',', '.', regex=False),
        errors='coerce'
    )

df.head(10)

,Localidade,Variável,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Abadia de Goiás,NaN,330195.67,726987.76,566675.99,625422.82,682545.53,887641.14,1304629,2409683,3396983,0,3101003
1,Abadiânia,NaN,8037554.05,10224774.03,8207670.93,5867364.20,12149754.18,4823481.46,7001505,13228345,14931771,1247010,10357766
2,Acreúna,NaN,14383002.58,13631427.66,7261516.43,6932883.38,8259436.29,7065726.58,6453869,6836953,14942521,4326823,8627573
3,Adelândia,NaN,2602870.67,2437096.08,1676603.53,1438599.15,2389589.90,2218052.03,3459716,4529872,10477717,1956258,9923722
4,Água Fria de Goiás,NaN,2488538.70,3674710.53,1416654.80,874106.93,9283948.96,4196060.34,5588390,1512845,5446464,2065800,9611876
5,Água Limpa,NaN,6230670.51,6545564.97,6902699.44,6512622.13,6918863.78,9057960.49,10561636,12179950,11971855,7063437,25725169
6,Águas Lindas de Goiás,NaN,19526.40,19526.40,186639.31,639760.35,17315.13,240000.00,0,0,0,0,496440
7,Alexânia,NaN,3911909.02,3802564.57,4398177.42,5505638.98,5542004.81,3422205.42,4892776,11095078,18885971,1554520,10043363
8,Aloândia,NaN,1654575.26,1544892.14,2291292.82,1743459.16,3403865.33,2423760.94,2283361,7554189,5328966,4585950,5615039
9,Alto Horizonte,NaN,5701834.54,4462831.07,6526401.07,4785263.38,6292594.86,6222370.20,6960098,4740519,9301153,2735416,14007676

In [28]:
tipos = df['2020'].apply(type)
tipos.head(10)

0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: 2020, dtype: object

In [30]:

numeric_cols = df.select_dtypes(include=['float', 'int']).columns


df[numeric_cols] = df[numeric_cols].round(2)

In [32]:

df["Md_Invest"] = df.iloc[:, 1:].mean(axis=1)


df["Md_Invest"] = df["Md_Invest"].round(2)

In [34]:
mean_values = df.iloc[:, 1:].mean()


nova_linha = ["Média"] + mean_values.tolist()


linha_media = pd.DataFrame([nova_linha], columns=df.columns)


df = pd.concat([df, linha_media], ignore_index=True)

In [35]:

st.set_page_config(layout="wide")


st.title('Dashboard Financeiro - Agro Goiás - 2014-2024')
st.write('Dashboard Financeiro - Tabela')


df["Md_Invest"] = df.iloc[:, 1:].mean(axis=1)
df["Md_Invest"] = df["Md_Invest"].round(2)
st.dataframe(df.style.format({'Md_Invest': '{:.2f}'}))
st.dataframe(df.head())

2026-04-20 21:26:04.827 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-20 21:26:04.832 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-20 21:26:05.091
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\nicol\AppData\Roaming\Python\Python314\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-04-20 21:26:05.092 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-20 21:26:05.094 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-20 21:26:05.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-20 21:26:05.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-20 21:26:05.096 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-20 21:26:06.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-20 21:26:06.180 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-20 21:26:06.181 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-20 21:26:06.182 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-20 21:26:06.187 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-20 21:26:06.188 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-20 21:26:06.188 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()